USE IDB;
GO
DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql += 'ALTER TABLE ' + QUOTENAME(TABLE_SCHEMA) + '.' + QUOTENAME(TABLE_NAME) +
               ' DROP CONSTRAINT ' + QUOTENAME(CONSTRAINT_NAME) + '; '
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'FOREIGN KEY';

EXEC sp_executesql @sql;
DROP TABLE IF EXISTS City;
DROP TABLE IF EXISTS RepresentativeOffice;
DROP TABLE IF EXISTS Store;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS TouristCustomer;
DROP TABLE IF EXISTS PostalCustomer;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS StoredItem;
DROP TABLE IF EXISTS OrderItem;
DROP TABLE IF EXISTS [Order];
